services:
  app:
    image: sharevb/it-tools:2026.1.4
    container_name: it-tools
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$'
      - wud.trigger.exclude=docker.autoupdate
    ports:
      - 8080:8080
    networks:
      - ittools

networks:
  ittools:
    name: ittools-network
    external: true
