services:
  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - 4000:3000/tcp # only required during initial setup
      - 1180:80/tcp # web interface after setup
      - 53:53/tcp # dns
      - 53:53/udp # dns
      # - 67:67/udp # dhcp
      # - 68:68/tcp # dhcp
      # - 68:68/udp # dhcp
      # - 784:784/udp # dns-over-quic
      # - 853:853/tcp # dns over tls
      # - 853:853/udp # dns over tls
      # - 5443:5443/tcp # dnscrypt
      # - 5443:5443/udp # dnscrypt
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
     - proxy

networks:
  proxy:
    name: proxy-bridge
    external: true
