---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Hosts:
    - Proxmox - DAGOBAH:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
        description: Virtualization Host
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
            fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
            username: {{HOMEPAGE_VAR_WIDGET_PROX_USER}}
            password: {{HOMEPAGE_VAR_WIDGET_PROX_PASS}}
            node: DAGOBAH
    - Proxmox - KAMINO:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
        description: Virtualization Host
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_WIDGET_PROX_URL}}
            fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
            username: {{HOMEPAGE_VAR_WIDGET_PROX_USER}}
            password: {{HOMEPAGE_VAR_WIDGET_PROX_PASS}}
            node: KAMINO

    - Portainer:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_PORT_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_PORT_URL}}
        description: Container Management
        widget:
            type: portainer
            url: {{HOMEPAGE_VAR_WIDGET_PORT_URL}}
            fields: ["running", "stopped", "total"]
            env: 1
            key: {{HOMEPAGE_VAR_WIDGET_PORT_APITOKEN}}

- Development:
    - Gitea:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_GITEA_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_GITEA_OPENURL}}
        description: Git Repositories
        widget:
            type: gitea
            url: {{HOMEPAGE_VAR_WIDGET_GITEA_URL}}
            fields: ["notifications", "issues", "pulls"]
            key: {{HOMEPAGE_VAR_WIDGET_GITEA_APITOKEN}}

    # - api:

    # - api-qa:

    # - tools:

- Network:
    - AdGuard:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_ADG_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_ADG_URL}}
        description: DNS and Ad Blocking
        widget:
            type: adguard
            url: {{HOMEPAGE_VAR_WIDGET_ADG_URL}}
            field: ["queries", "blocked", "filtered", "latency"]
            username: {{HOMEPAGE_VAR_WIDGET_ADG_USER}}
            password: {{HOMEPAGE_VAR_WIDGET_ADG_PASS}}

    - Nginx Proxy Manager:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_NPM_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_NPM_URL}}
        description: Reverse Proxy
        widget:
            type: npm
            url: {{HOMEPAGE_VAR_WIDGET_NPM_URL}}
            username: {{HOMEPAGE_VAR_WIDGET_NPM_USER}}
            password: {{HOMEPAGE_VAR_WIDGET_NPM_PASS}}

    - Speedtest-Tracker:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_STT_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_STT_URL}}
        description: Network Speed Tracking
        widget:
            type: speedtest
            url: {{HOMEPAGE_VAR_WIDGET_STT_URL}}
            fields: ["download", "upload", "ping"]

    - Uptime-Kuma:
        # icon:
        ping: {{HOMEPAGE_VAR_WIDGET_UTK_URL}}
        href: {{HOMEPAGE_VAR_WIDGET_UTK_URL}}
        description: Tracking network uptime
        widget:
            type: uptimekuma
            url: {{HOMEPAGE_VAR_WIDGET_UTK_URL}}
            fields: ["up", "down", "uptime", "incident"]
            slug: homepage

#     - bookstack:

# - Hosts:
#     - HUNT-PC1:

#     - CORUSCANT:

#     - KAMINO:

#     - DAGOBAH:

# - Virtualization:
#     - sqlprod01:

#     - docker01:

#     - git01:

#     - dc02:

#     - bookstack02:

#     - ftp03:

#     - automate03:

#     - fs02:

#     - iis01:

#     - sqldev01:

#     - test-ws19:

#     - opn01:

# - External:
#     - Ghost:


# TODO: look into the following widgets
# Crowdsec - on exposed services, i.e. ftp03
# Glaces - monitors computer stats
# Minecraft - since why not?
# OpenWeatherMap - weather is always a nice touch
# Watchtower - update base container images
# wg-easy - VPN with web UI
