---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true

- search:
    provider: [google, bing, duckduckgo]
    showSearchSuggestions: true
    target: _blank

- datetime:
    locale: en
    text_size: x1
    format:
        dateStyle: medium
        timeStyle: long
        hour12: true
